### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by mond-cz** [gabrielmontagne/blender-addon-load-subtitles-to-vse#1]
I got an error for import, what's the problem with codec? I tried it in 2.77a and 2.78 with several SRT files with english and czech language. Thanks for help.

BTW wasn't enough clear for me to hit space bar to bring operator, I was looking for some button or row in import list.

`location: <unknown location>:-1
Traceback (most recent call last):
  File "/Users/filip/Library/Application Support/Blender/2.78/scripts/addons/blender-addon-load-subtitles-to-vse-master/__init__.py", line 40, in execute
    subtitles = srtopen(self.properties.filepath)
  File "/Users/filip/Library/Application Support/Blender/2.78/scripts/addons/blender-addon-load-subtitles-to-vse-master/pysrt/srtfile.py", line 153, in open
    new_file.read(source_file, error_handling=error_handling)
  File "/Users/filip/Library/Application Support/Blender/2.78/scripts/addons/blender-addon-load-subtitles-to-vse-master/pysrt/srtfile.py", line 180, in read
    self.eol = self._guess_eol(source_file)
  File "/Users/filip/Library/Application Support/Blender/2.78/scripts/addons/blender-addon-load-subtitles-to-vse-master/pysrt/srtfile.py", line 257, in _guess_eol
    first_line = cls._get_first_line(string_iterable)
  File "/Users/filip/Library/Application Support/Blender/2.78/scripts/addons/blender-addon-load-subtitles-to-vse-master/pysrt/srtfile.py", line 269, in _get_first_line
    first_line = next(iter(string_iterable))
  File "/Users/filip/Downloads/blender/./blender.app/Contents/MacOS/../Resources/2.78/python/lib/python3.5/codecs.py", line 711, in __next__
    return next(self.reader)
  File "/Users/filip/Downloads/blender/./blender.app/Contents/MacOS/../Resources/2.78/python/lib/python3.5/codecs.py", line 642, in __next__
    line = self.readline()
  File "/Users/filip/Downloads/blender/./blender.app/Contents/MacOS/../Resources/2.78/python/lib/python3.5/codecs.py", line 555, in readline
    data = self.read(readsize, firstline=True)
  File "/Users/filip/Downloads/blender/./blender.app/Contents/MacOS/../Resources/2.78/python/lib/python3.5/codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

location: <unknown location>:-1
`

**Comment by mond-cz** [comment]
OK, I resaved SRT in UTF-8, solved.
Sorry

**Comment by gabrielmontagne** [comment]
Hi @mond-cz , thanks for the report.  Yes, the subtitles need to be in UTF-8 and, yes, there are no instructions on how this should work.  I'll add a couple of notes to the README.

I'm glad that you got it to work in the end.
